- src/utils.js
- test/spec/define.js
The current implementation of ```pascalToDash``` does not account for acronyms. This is slightly problematic when using the ```define``` function with a map of Hybrids descriptor objects because a key like ```XYZComponent``` is not correctly converted to a tag name like ```xyz-component```.
> Add support for acronyms (i.e. XYZComponent) in hybrids map.

- docs/template-engine/styling.md
Adds webpack instructions for adding PostCSS.
Minor: “webpack” is always spelled lowercase, at least last time I checked (the core team decided this 🤷‍♂️).
> Add PostCSS instructions

- docs/built-in-factories/property.md
- docs/built-in-factories/render.md
- docs/core-concepts/definition.md
- docs/core-concepts/descriptors.md
- src/cache.js
- src/children.js
- src/define.js
- src/emitter.js
- src/parent.js
- src/render.js
- src/template/core.js
- src/template/index.js
- src/template/resolvers/array.js
- src/utils.js
- test/helpers.js
- test/spec/cache.js
- test/spec/children.js
- test/spec/define.js
- test/spec/emitter.js
- test/spec/html.js
- test/spec/parent.js
- test/spec/property.js
- test/spec/render.js
Change detection mechanism relays on DOM events. This has two significant drawbacks:
* We can only attach cache mechanism to objects that are HTML elements
* DOM events API is slow and complicates observing children factory due to listening bubbling event
This PR introduces a new change detection mechanism:
* It's based on internal emitter
* Allows observing changes in other properties like it was implemented in `render` factory (scheduler)
* Decauples cache from HTML elements - allows creating `store` factory with objects related to HTML elements with a proper cache mechanism connected between them
From now, instead of using `@invalidate` event, you have to use the `observe` method of the descriptor:
```javascript
MyElement = {
property: {
get(host, lastValue) {...},
set(host, value) …
```
> feat: change detection mechanism refactor

- src/property.js
Looks like we're referencing an undeclared variable `v` and will always print out `Assigned value must be an object: undefined`
> Fixing error message

- docs/core-concepts/introduction.md
The lifecycle image shows up when viewed in github (where the relative path is correct) but doesn't show up on the official GitBook-driven website, https://hybrids.js.org/core-concepts/introduction (where the relative path is incorrect)
> Make lifecycle image path static

- package.json
- src/cache.js
- src/define.js
- src/emitter.js
- test/spec/cache.js
When contexts are created for observing value changes in complex dependency tree they might not be cleaned properly when the element is disconnected from the DOM. This PR fixes this by flattening deps structure with `contextStack` instead of deep tree of dependencies.
> Fix cache observer

- docs/README.md
- docs/misc/README.md
- docs/misc/typescript.md
- package.json
- src/render.js
- types/index.d.ts
This PR adds TypeScript definitions file (`types/index.d.ts`).  I think it covers almost all cases. At first, I tried to avoid passing generic types, and use descriptors to determine the type, but I think it is not possible.
From now in TS the original example from homepage of the docs can be written as follows:
```typescript
import { define, html, Hybrids } from 'hybrids';
interface SimpleCounter extends HTMLElement {
count: number;
}
export function increaseCount(host: SimpleCounter) {
host.count += 1;
}
export const SimpleCounter: Hybrids<SimpleCounter> = {
count: 0,
render: ({ count }) => html`
<button onclick="${increaseCount}">
Count: ${count}
</button>
`,
};
define('simple-counter', SimpleCounter);
```
What we have from types here:
* Interface of the definition have to extend …
> feat: TypeScript definitions

- docs/built-in-factories/render.md
- src/render.js
- test/spec/render.js
This PR changes two internal parts of the render factory and is related to #86 issue.
* Moves `attachShadow` from `connect()` to `get()` method - this allows calling `el.render()` before the property is connected. It might happen if in other property depends on render and it is called in `observe` or `connect` method
* Returns target from `flush()` - for direct call to update function - `el.render()` - this fixes possibility to create refs to internal parts as a public API of the element
> fix(render): allow update before schedule; render call should return target

- src/define.js
- test/spec/property.js
> fix(define): rewire own props values after upgrade

- docs/core-concepts/definition.md
- src/define.js
- test/spec/define.js
- types/index.d.ts
Allows generation of the Hybrid constructor without definition custom element.
```javascript
const MyElement = {};
const Constructor = define(null, MyElement);
customElements.define("my-custom-name", Constructor);
```
> feat(define): Hybrid constructor without definition in the registry

- docs/basics/definition.md
Since the "package" exports result of `define` call as a default the "customer" can't use named import
> docs: fix import statement in definition.md

- docs/template-engine/event-listeners.md
- src/define.js
- src/template/helpers.js
- src/template/resolvers/array.js
- test/spec/html.js
> fix(html): html.set uses detail.value for general element support

- types/index.d.ts
use module instead of namespace
> fix(types): uses 'export = not' and cannot be used with 'export *' Error

- README.md
- docs/README.md
- docs/basics/definition.md
- docs/basics/descriptor.md
- docs/core-features/events.md
- docs/core-features/parent-children.md
- docs/core-features/property.md
- docs/core-features/render.md
- docs/getting-started/concepts.md
- docs/misc/api-reference.md
- docs/misc/typescript.md
- docs/store/model.md
- docs/store/overview.md
- docs/store/storage.md
- docs/store/usage.md
- docs/template-engine/dependencies.md
- docs/template-engine/event-listeners.md
- docs/template-engine/styling.md
- docs/template-engine/values.md
- src/define.js
- src/template/index.js
- test/spec/children.js
- test/spec/define.js
- test/spec/html.js
- types/index.d.ts
BREAKING CHANGE: Passing a map of components to the `define()` function is no longer supported. Object argument will be interpreted as a tagged component definition. A preferred way to refactor old code is to extend the definition of the component with the `tag` property, and pass definitions to the `define()` function as a list of arguments. If your definition contains `tag` property with another purpose, you can still use the `define(tagName, descriptors)` version.
From:
```js
const MyElement = { ... };
const MyOtherElement = { ... };
define({ MyElement, MyOtherElement });
```
To:
```js
const MyElement = { tag: "my-element", .. };
const MyOtherElement = { tag: "my-other-element", ... };
define(MyElement, MyOtherElement);
```
> feat(define): replace call for a map of components with tagged components

- docs/store/model.md
- docs/store/storage.md
- src/store.js
- test/spec/store.js
BREAKING CHANGE: From now, for external storage, the result of the list action will not invalidate when the model instance is changed. The items within the list are still updated, but deletion or creating a model instance won't update the list unless you set the storage `loose` option to `true`. However, the default value change only applies to listing enumerable models with external storage, which can be changed by the user. For most of the case, you should ok, without additional change in the code.
> fix(store): set the storage loose option default value to `false`

- docs/component-model/parent-children.md
- docs/misc/api-reference.md
- src/children.js
- src/parent.js
- test/spec/children.js
- test/spec/parent.js
Hi @smalluban!
Here's a totally unsolicited (but helpful) feature which you might find complementary to the existing parent/children factories...
For some complex components which reference parent and child elements based on element context, access to the host element is helpful. This can be done without a breaking change and creates some options for advanced component interactions.
For example, to get a parent which exposes a particular property name:
```js
const MyChildComponent = define({
tag: 'my-child-component',
context: '__ctx__',
contextProvider: parent((el, {context}) => el.hasOwnProperty(context)),
// ...
})
```
Another use case:
```js
const ChildElementCounter = define({
tag: 'child-element-counter',
childTag: '',
children: children((el, {childTag}) => el.tag.toLowerCase() === …
```
> fix(parent/child): Add host argument to parent and child factories.

- docs/component-model/layout-engine.md
- docs/component-model/templates.md
- docs/misc/api-reference.md
- docs/router/usage.md
- src/router.js
- src/template/core.js
- src/template/helpers/index.js
- src/template/helpers/resolve.js
- src/template/helpers/set.js
- src/template/helpers/transition.js
- src/template/index.js
- src/template/layout.js
- src/template/methods.js
- test/spec/html.js
- test/spec/layout.js
- test/spec/router.js
- types/index.d.ts
Fixes #193.
The PR adds support for Transition API recently added to Chrome 111. It extends `html` helpers with `html.transition` method, which should wrap the top-most component from the tree structure, where an update of the content/render should trigger `startViewTransition` process.
It's the first iteration of the implementation, the API can be changed if you have a simpler/better idea. If other features of the Transition API might be required, the `html.transition(fn, options = { ... })` can be extended with some `options` object as a second argument (?).
Simple example:
```js
define({
tag: "test-html-transition",
content: ({ value }) =>
html.transition(
html`<div>${value}</div>`,
),
});
```
The layout engine was extended with `view` rule, which allows adding view transition name, …
> feat(html): Add support for Transition API and `use` helper method

- src/cache.js
- test/spec/define.js
Relates to #229 
Still updating properties in a chain of the observer can lead to out-of-date UI, as the `render` method is added to the emitter queue when the first of its dependencies has changed. Added test to this PR shows that case - render is called after the `prop1` observer, so the `prop1` and `prop2` are updated, but before the `prop3` (it is added to the queue when render is there already).
However, the PR fixes the issue where the state after that action is broken, and `render` has no deps anymore (before calling `host.prop3 = ...` cleared out deps/contexts of a whole tree, so render has no deps then, but it also will not be called, as it was called already).
> fix(cache): Clear deps and context when get value from cache

- types/index.d.ts
If the object that the user uses to create the model has an "id" property defined, then it must be a string. 
See https://github.com/hybridsjs/hybrids/commit/faec4c67cc255b60a705cd86c2ed8ef0f4703e3b
> Update generic of type `Model<M>`

- src/cache.js
- test/spec/html.js
It's related to #273.
The test proves that assert of the property of hybrid element inside of the render function (by the template engine expression) does not throw an error.
> fix(cache): throw when update internal properties of the target

- test/types/define/property-descriptor.ts
- types/index.d.ts
A property with a getter was throwing a typing error, a descriptor with a getter was also throwing a typing error. Fixed
> fix(define) types of property and descriptor
